#' Fitting Models by OLS
#'
#' @description This function generates multiple regression models
#' by passing multiple baseline models
#' (two-sided formula consisting of outcomes and treatments) and
#' multiple covariate models (ons-sided formula) as arguments.
#' In addition, the generated regression model is fitted
#' by the least squares method of the `lm_robust` function
#' in the {estimatr} package.
#'
#' @param basemod list of baseline model.
#' Baseline model is specified by `y ~ d`
#' where `y` is outcome, and `d` is treatments.
#' @param xmod list of covariate model.
#' Covariate model is specified by one-sided formula like `~ x1 + x2`.
#' @param include_onlyd logical.
#' Whether to estimate a model without covariates.
#' @param base character. Name of the control.
#' This argument is passed when treatment variable is not factor.
#' @param data data or list of data.
#' Length of data list must be same as
#' length of model list generated by genmod.
#' @param \dots other arguments passed in `estimatr::lm_robust`
#'
#' @return list with RCT_OLS class. `.$model` is a list of fitted models.
#' `.$res` is a list of result.
#'
#' @importFrom estimatr lm_robust
#' @export
#'
#' @examples
#' # DGP
#' set.seed(120511)
#' n <- 1000
#' x1 <- rnorm(n); x2 <- rnorm(n)
#' d <- sample(c("A", "B", "C"), size = n, replace = TRUE)
#'
#' ya <- 0.2 + 0.5 * x1 + 0.01 * x2
#' yb <- 1.2 + 0.3 * x2
#' yc <- -1 - 0.2 * x1 + 0.5 * x2
#' y <- ifelse(d == "A", ya, ifelse(d == "B", yb, yc))
#'
#' dt <- data.frame(y, d, x1, x2)
#'
#' # Run regression
#' est <- rct_lm(y ~ d, xmod = ~ x1 + x2, data = dt)
#' summary(est)
#'
rct_lm <- function(
  basemod, xmod = NULL, include_onlyd = TRUE,
  base = NULL, data, ...
) {
  # generate model list
  modlist <- genmod(basemod, xmod, include_onlyd)
  # estimation
  if (!is.data.frame(data)) {
    if (length(data) != length(modlist)) {
      stop("Model and data list must be same length.")
    }
    est <- lapply(seq_len(modlist), function(i) {
      d <- all.vars(modlist[[i]])[2]
      if (!is.factor(data[[i]][[d]])) {
        data[[i]][[d]] <- factorlize(data[[i]][[d]], base)
      }
      estimatr::lm_robust(modlist[[i]], data[[i]], ...)
    })
  } else {
    est <- lapply(modlist, function(x) {
      d <- all.vars(x)[[2]]
      if (!is.factor(data[[d]])) data[[d]] <- factorlize(data[[d]], base)
      estimatr::lm_robust(x, data = data, ...)
    })
  }
  res <- list(model = modlist, res = est)
  class(res) <- append(class(res), "RCT_OLS")
  res
}

#' Summary Method for RCT_OLS class
#'
#' @param object object RCT_OLS class
#' @param \dots other arguments passing in summary function.
#'
#' @method summary RCT_OLS
#' @export
#'
summary.RCT_OLS <- function(object, ...) {
  lapply(object$res, summary, ...)
}